import { sql } from "drizzle-orm";
import {
  check,
  boolean,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { documentEvidenceAssets } from "./evidence";
import { organizations } from "./identity";
import { journalEntries } from "./journals";
import { accountCombinations, legalEntities, ledgers } from "./ledger";

export const assetCategories = pgTable(
  "asset_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    legalEntityId: uuid("legal_entity_id").notNull(),
    ledgerId: uuid("ledger_id").notNull(),
    kind: text("kind").notNull(),
    categoryKey: uuid("category_key").notNull(),
    code: text("code").notNull(),
    displayName: text("display_name").notNull(),
    costAccountCombinationId: uuid("cost_account_combination_id").notNull(),
    contraAccountCombinationId: uuid("contra_account_combination_id"),
    expenseAccountCombinationId: uuid("expense_account_combination_id").notNull(),
    impairmentAccountCombinationId: uuid("impairment_account_combination_id"),
    disposalAccountCombinationId: uuid("disposal_account_combination_id"),
    active: boolean("active").notNull().default(true),
    version: integer("version").notNull().default(1),
    supersedesCategoryId: uuid("supersedes_category_id"),
    effectiveFrom: date("effective_from").notNull(),
    reason: text("reason").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    commandHash: text("command_hash").notNull(),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_categories_org_id_unique").on(table.organizationId, table.id),
    uniqueIndex("asset_categories_scope_version_unique").on(table.organizationId, table.ledgerId, table.code, table.version),
    uniqueIndex("asset_categories_org_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    uniqueIndex("asset_categories_key_version_unique").on(table.organizationId, table.categoryKey, table.version),
    uniqueIndex("asset_categories_org_supersedes_unique").on(table.organizationId, table.supersedesCategoryId),
    index("asset_categories_org_kind_idx").on(table.organizationId, table.kind, table.displayName),
    check("asset_categories_kind_check", sql.raw("kind IN ('TANGIBLE', 'INTANGIBLE', 'PREPAID')")),
    check("asset_categories_mapping_check", sql.raw("(kind = 'PREPAID') OR contra_account_combination_id IS NOT NULL")),
    check("asset_categories_version_check", sql.raw("version > 0")),
    check("asset_categories_reason_check", sql.raw("char_length(btrim(reason)) BETWEEN 8 AND 500")),
    check("asset_categories_command_hash_check", sql.raw("command_hash ~ '^[a-f0-9]{64}$'")),
    foreignKey({ columns: [table.organizationId, table.legalEntityId], foreignColumns: [legalEntities.organizationId, legalEntities.id], name: "asset_categories_org_entity_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.ledgerId], foreignColumns: [ledgers.organizationId, ledgers.id], name: "asset_categories_org_ledger_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.costAccountCombinationId], foreignColumns: [accountCombinations.organizationId, accountCombinations.id], name: "asset_categories_org_cost_account_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.contraAccountCombinationId], foreignColumns: [accountCombinations.organizationId, accountCombinations.id], name: "asset_categories_org_contra_account_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.expenseAccountCombinationId], foreignColumns: [accountCombinations.organizationId, accountCombinations.id], name: "asset_categories_org_expense_account_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.impairmentAccountCombinationId], foreignColumns: [accountCombinations.organizationId, accountCombinations.id], name: "asset_categories_org_impairment_account_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.disposalAccountCombinationId], foreignColumns: [accountCombinations.organizationId, accountCombinations.id], name: "asset_categories_org_disposal_account_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.supersedesCategoryId], foreignColumns: [table.organizationId, table.id], name: "asset_categories_org_supersedes_fk" }).onDelete("restrict"),
  ],
);

export const assetRegister = pgTable(
  "asset_register",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    categoryId: uuid("category_id").notNull(),
    legalEntityId: uuid("legal_entity_id").notNull(),
    ledgerId: uuid("ledger_id").notNull(),
    kind: text("kind").notNull(),
    assetNumber: text("asset_number").notNull(),
    displayName: text("display_name").notNull(),
    description: text("description"),
    classification: text("classification").notNull().default("FINITE_LIFE"),
    acquisitionDate: date("acquisition_date").notNull(),
    inServiceOn: date("in_service_on").notNull(),
    scheduleEndOn: date("schedule_end_on"),
    cost: numeric("cost", { precision: 38, scale: 9 }).notNull(),
    residualValue: numeric("residual_value", { precision: 38, scale: 9 }).notNull().default("0"),
    usefulLifeMonths: integer("useful_life_months"),
    recognitionFrequency: text("recognition_frequency").notNull().default("MONTHLY"),
    location: text("location"),
    custodian: text("custodian"),
    vendorName: text("vendor_name"),
    sourceReference: text("source_reference"),
    evidenceAssetId: uuid("evidence_asset_id"),
    status: text("status").notNull().default("ACTIVE"),
    recognizedToDate: numeric("recognized_to_date", { precision: 38, scale: 9 }).notNull().default("0"),
    idempotencyKey: text("idempotency_key").notNull(),
    commandHash: text("command_hash").notNull(),
    version: integer("version").notNull().default(1),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_register_org_id_unique").on(table.organizationId, table.id),
    uniqueIndex("asset_register_org_number_unique").on(table.organizationId, table.assetNumber),
    uniqueIndex("asset_register_org_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    index("asset_register_org_kind_status_idx").on(table.organizationId, table.kind, table.status),
    check("asset_register_kind_check", sql.raw("kind IN ('TANGIBLE', 'INTANGIBLE', 'PREPAID')")),
    check("asset_register_classification_check", sql.raw("classification IN ('FINITE_LIFE', 'INDEFINITE_LIFE')")),
    check("asset_register_status_check", sql.raw("status IN ('ACTIVE', 'IMPAIRED', 'DISPOSED', 'RETIRED', 'TERMINATED')")),
    check("asset_register_amount_check", sql.raw("cost > 0 AND residual_value >= 0 AND residual_value <= cost AND recognized_to_date >= 0 AND recognized_to_date <= cost")),
    check("asset_register_schedule_check", sql.raw("(classification = 'INDEFINITE_LIFE' AND kind = 'INTANGIBLE' AND useful_life_months IS NULL AND schedule_end_on IS NULL) OR (classification = 'FINITE_LIFE' AND useful_life_months BETWEEN 1 AND 1200 AND schedule_end_on IS NOT NULL)")),
    check("asset_register_dates_check", sql.raw("acquisition_date <= in_service_on AND (schedule_end_on IS NULL OR schedule_end_on >= in_service_on)")),
    check("asset_register_command_hash_check", sql.raw("command_hash ~ '^[a-f0-9]{64}$'")),
    foreignKey({ columns: [table.organizationId, table.categoryId], foreignColumns: [assetCategories.organizationId, assetCategories.id], name: "asset_register_org_category_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.legalEntityId], foreignColumns: [legalEntities.organizationId, legalEntities.id], name: "asset_register_org_entity_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.ledgerId], foreignColumns: [ledgers.organizationId, ledgers.id], name: "asset_register_org_ledger_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.evidenceAssetId], foreignColumns: [documentEvidenceAssets.organizationId, documentEvidenceAssets.id], name: "asset_register_org_evidence_fk" }).onDelete("restrict"),
  ],
);

export const assetScheduleEntries = pgTable(
  "asset_schedule_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    assetId: uuid("asset_id").notNull(),
    sequenceNumber: integer("sequence_number").notNull(),
    periodStartOn: date("period_start_on").notNull(),
    periodEndOn: date("period_end_on").notNull(),
    dueOn: date("due_on").notNull(),
    amount: numeric("amount", { precision: 38, scale: 9 }).notNull(),
    status: text("status").notNull().default("DUE"),
    journalEntryId: uuid("journal_entry_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    version: integer("version").notNull().default(1),
    adjustmentReason: text("adjustment_reason"),
    postedAt: timestamp("posted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_schedule_entries_org_id_unique").on(table.organizationId, table.id),
    uniqueIndex("asset_schedule_entries_asset_sequence_unique").on(table.assetId, table.sequenceNumber),
    uniqueIndex("asset_schedule_entries_org_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    index("asset_schedule_entries_org_due_idx").on(table.organizationId, table.status, table.dueOn),
    check("asset_schedule_entries_status_check", sql.raw("status IN ('DUE', 'DRAFTED', 'POSTED', 'SKIPPED', 'ADJUSTED', 'REVERSED')")),
    check("asset_schedule_entries_amount_check", sql.raw("amount > 0 AND sequence_number > 0 AND period_start_on <= period_end_on AND due_on >= period_start_on")),
    check("asset_schedule_entries_journal_check", sql.raw("(status = 'DUE' AND journal_entry_id IS NULL) OR (status <> 'DUE')")),
    foreignKey({ columns: [table.organizationId, table.assetId], foreignColumns: [assetRegister.organizationId, assetRegister.id], name: "asset_schedule_entries_org_asset_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.journalEntryId], foreignColumns: [journalEntries.organizationId, journalEntries.id], name: "asset_schedule_entries_org_journal_fk" }).onDelete("restrict"),
  ],
);

export const assetLifecycleEvents = pgTable(
  "asset_lifecycle_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    assetId: uuid("asset_id").notNull(),
    eventType: text("event_type").notNull(),
    effectiveOn: date("effective_on").notNull(),
    amount: numeric("amount", { precision: 38, scale: 9 }),
    details: jsonb("details").notNull().default({}),
    journalEntryId: uuid("journal_entry_id"),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_lifecycle_events_org_id_unique").on(table.organizationId, table.id),
    index("asset_lifecycle_events_org_asset_idx").on(table.organizationId, table.assetId, table.createdAt),
    check("asset_lifecycle_events_type_check", sql.raw("event_type IN ('CREATED', 'SCHEDULED', 'DRAFT_CREATED', 'POSTED', 'IMPAIRED', 'TRANSFERRED', 'DISPOSED', 'RETIRED', 'TERMINATED', 'ADJUSTED', 'REVERSED')")),
    foreignKey({ columns: [table.organizationId, table.assetId], foreignColumns: [assetRegister.organizationId, assetRegister.id], name: "asset_lifecycle_events_org_asset_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.journalEntryId], foreignColumns: [journalEntries.organizationId, journalEntries.id], name: "asset_lifecycle_events_org_journal_fk" }).onDelete("restrict"),
  ],
);

/** Immutable, reviewed tax classification versions. Book schedule fields stay on asset_register. */
export const assetTaxClassifications = pgTable(
  "asset_tax_classifications",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    assetId: uuid("asset_id").notNull(),
    jurisdiction: text("jurisdiction").notNull(),
    regimeKey: text("regime_key").notNull(),
    classKey: text("class_key").notNull(),
    poolKey: text("pool_key").notNull(),
    prescribedRate: numeric("prescribed_rate", { precision: 12, scale: 9 }).notNull(),
    availableForUseOn: date("available_for_use_on").notNull(),
    businessUsePercent: numeric("business_use_percent", { precision: 7, scale: 4 }).notNull(),
    costBeforeSalesTax: numeric("cost_before_sales_tax", { precision: 38, scale: 9 }).notNull(),
    recoverableSalesTax: numeric("recoverable_sales_tax", { precision: 38, scale: 9 }).notNull().default("0"),
    nonRecoverableSalesTax: numeric("non_recoverable_sales_tax", { precision: 38, scale: 9 }).notNull().default("0"),
    taxCapitalCost: numeric("tax_capital_cost", { precision: 38, scale: 9 }).notNull(),
    assistance: numeric("assistance", { precision: 38, scale: 9 }).notNull().default("0"),
    ruleKey: text("rule_key").notNull(),
    ruleVersion: text("rule_version").notNull(),
    authorityStatus: text("authority_status").notNull(),
    sourceUri: text("source_uri").notNull(),
    eligibilityEvidence: text("eligibility_evidence").notNull(),
    elections: jsonb("elections").notNull().default([]),
    version: integer("version").notNull(),
    supersedesClassificationId: uuid("supersedes_classification_id"),
    reason: text("reason").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    commandHash: text("command_hash").notNull(),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_tax_classifications_org_id_unique").on(table.organizationId, table.id),
    uniqueIndex("asset_tax_classifications_asset_version_unique").on(table.assetId, table.version),
    uniqueIndex("asset_tax_classifications_org_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    uniqueIndex("asset_tax_classifications_org_supersedes_unique").on(table.organizationId, table.supersedesClassificationId),
    index("asset_tax_classifications_org_asset_idx").on(table.organizationId, table.assetId, table.version),
    check("asset_tax_classifications_rate_check", sql.raw("prescribed_rate > 0 AND prescribed_rate <= 1")),
    check("asset_tax_classifications_use_check", sql.raw("business_use_percent > 0 AND business_use_percent <= 100")),
    check("asset_tax_classifications_amount_check", sql.raw("cost_before_sales_tax > 0 AND recoverable_sales_tax >= 0 AND non_recoverable_sales_tax >= 0 AND tax_capital_cost = cost_before_sales_tax + non_recoverable_sales_tax AND assistance >= 0 AND assistance <= tax_capital_cost")),
    check("asset_tax_classifications_authority_check", sql.raw("authority_status IN ('ENACTED', 'PROPOSED')")),
    check("asset_tax_classifications_hash_check", sql.raw("command_hash ~ '^[a-f0-9]{64}$'")),
    check("asset_tax_classifications_elections_check", sql.raw("jsonb_typeof(elections) = 'array'")),
    foreignKey({ columns: [table.organizationId, table.assetId], foreignColumns: [assetRegister.organizationId, assetRegister.id], name: "asset_tax_classifications_org_asset_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.supersedesClassificationId], foreignColumns: [table.organizationId, table.id], name: "asset_tax_classifications_org_supersedes_fk" }).onDelete("restrict"),
  ],
);

/** A schedule is a frozen calculation snapshot; recalculation appends a superseding version. */
export const assetTaxSchedules = pgTable(
  "asset_tax_schedules",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "restrict" }),
    assetId: uuid("asset_id").notNull(),
    classificationId: uuid("classification_id").notNull(),
    taxYearStart: integer("tax_year_start").notNull(),
    taxYearEnd: integer("tax_year_end").notNull(),
    scheduleSnapshot: jsonb("schedule_snapshot").notNull(),
    maximumCca: numeric("maximum_cca", { precision: 38, scale: 9 }).notNull(),
    claimedCca: numeric("claimed_cca", { precision: 38, scale: 9 }).notNull(),
    closingUcc: numeric("closing_ucc", { precision: 38, scale: 9 }).notNull(),
    version: integer("version").notNull(),
    supersedesScheduleId: uuid("supersedes_schedule_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    commandHash: text("command_hash").notNull(),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("asset_tax_schedules_org_id_unique").on(table.organizationId, table.id),
    uniqueIndex("asset_tax_schedules_scope_version_unique").on(table.assetId, table.classificationId, table.taxYearStart, table.taxYearEnd, table.version),
    uniqueIndex("asset_tax_schedules_org_idempotency_unique").on(table.organizationId, table.idempotencyKey),
    uniqueIndex("asset_tax_schedules_org_supersedes_unique").on(table.organizationId, table.supersedesScheduleId),
    index("asset_tax_schedules_org_asset_idx").on(table.organizationId, table.assetId, table.taxYearEnd),
    check("asset_tax_schedules_year_check", sql.raw("tax_year_start BETWEEN 1900 AND 2500 AND tax_year_end BETWEEN tax_year_start AND 2500")),
    check("asset_tax_schedules_amount_check", sql.raw("maximum_cca >= 0 AND claimed_cca >= 0 AND claimed_cca <= maximum_cca AND closing_ucc >= 0")),
    check("asset_tax_schedules_snapshot_check", sql.raw("jsonb_typeof(schedule_snapshot) = 'array'")),
    check("asset_tax_schedules_hash_check", sql.raw("command_hash ~ '^[a-f0-9]{64}$'")),
    foreignKey({ columns: [table.organizationId, table.assetId], foreignColumns: [assetRegister.organizationId, assetRegister.id], name: "asset_tax_schedules_org_asset_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.classificationId], foreignColumns: [assetTaxClassifications.organizationId, assetTaxClassifications.id], name: "asset_tax_schedules_org_classification_fk" }).onDelete("restrict"),
    foreignKey({ columns: [table.organizationId, table.supersedesScheduleId], foreignColumns: [table.organizationId, table.id], name: "asset_tax_schedules_org_supersedes_fk" }).onDelete("restrict"),
  ],
);
