import { randomBytes,randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it,vi } from "vitest";
import { Pool } from "pg";
import { closeDatabasePool,withTenantTransaction } from "@/db/transaction";
import { createManualJournal } from "@/modules/ledger/journal-service";
import { postJournal } from "@/modules/ledger/posting-service";
import { createBookingBatch,readBookingReport,postBookingBatch,refreshBookingReport,listBookingReports } from "@/modules/booking-reports/service";
import type { BookingReport } from "@/modules/booking-reports/service";
import * as capture from "@/modules/booking-reports/capture";
import type { BookingRecord } from "@/modules/booking-reports/model";
import { LocalRootKeyProvider,serializeWrappedKey,encryptField,serializeEncryptedField } from "@/security/organization-encryption";
import { loadOrganizationRootKek } from "@/security/root-secret";
import { buildBusinessDocumentSnapshot } from "@/modules/subledger/document-model";
import { appendSourceDocument } from "@/modules/subledger/ar-ap-persistence";
import { issueBusinessDocument,recordCustomerReceiptOrSupplierPayment } from "@/modules/subledger/ar-ap-service";
const run=process.env.TEST_DATABASE_URL&&process.env.TEST_APP_DATABASE_URL?describe:describe.skip;
const id={org:randomUUID(),actor:randomUUID(),member:randomUUID(),role:randomUUID(),entity:randomUUID(),ledger:randomUUID(),period:randomUUID(),revenue:randomUUID(),expense:randomUUID(),cash:randomUUID(),expenseCombination:randomUUID(),cashCombination:randomUUID(),outsider:randomUUID(),party:randomUUID(),partyAccount:randomUUID(),payable:randomUUID(),payableCombination:randomUUID(),liability:randomUUID(),liabilityCombination:randomUUID(),taxRegistration:randomUUID(),gainCombination:randomUUID()};
const context=()=>({organizationId:id.org,actorId:id.actor,requestId:randomUUID(),authMethod:"oidc",sourceSurface:"API" as const,reason:"Synthetic booking regression"});
run("immutable booking reports and authorized posting",()=>{
 const owner=new Pool({connectionString:process.env.TEST_DATABASE_URL});
 let review:BookingReport,posted:BookingReport,manual:BookingRecord;
 async function journalRecord(description="Synthetic booked journal") {const created=await createManualJournal({context:context(),legalEntityId:id.entity,ledgerId:id.ledger,periodId:id.period,accountingDate:"2025-12-15",purpose:"ROUTINE",description,idempotencyKey:randomUUID(),lines:[
 {accountCombinationId:id.expenseCombination,debitFunctional:"125.50",creditFunctional:"0",debitTransaction:"125.50",creditTransaction:"0",transactionCurrency:"CAD",fxRate:"1",fxRateSource:"functional",fxRateEffectiveAt:"2025-12-15T00:00:00Z"},
 {accountCombinationId:id.cashCombination,debitFunctional:"0",creditFunctional:"125.50",debitTransaction:"0",creditTransaction:"125.50",transactionCurrency:"CAD",fxRate:"1",fxRateSource:"functional",fxRateEffectiveAt:"2025-12-15T00:00:00Z"}]});
 const row=(await withTenantTransaction(context(),client=>client.query("SELECT app.compute_journal_content_hash(id) AS hash,coalesce(approval_version,0) AS version FROM journal_entries WHERE id=$1",[created.journalId]))).rows[0];return {type:"JOURNAL" as const,id:created.journalId,expectedVersion:row.version,expectedContentHash:row.hash};}
 const batch=(records:BookingRecord[])=>({legalEntityId:id.entity,ledgerId:id.ledger,title:"Synthetic booking review",records,reason:"Review synthetic entries",idempotencyKey:randomUUID()});
 beforeAll(async()=>{vi.stubEnv("DATABASE_URL",process.env.TEST_APP_DATABASE_URL!);vi.stubEnv("BUSINESS_WRITES_ENABLED","true");await closeDatabasePool();
    await owner.query("INSERT INTO organizations(id,slug,display_name,active,is_demo,organization_mode,writes_enabled_at) VALUES($1,$2,'Synthetic tax regression',true,false,'REAL',now())", [id.org, `tax-refresh-${id.org}`]);
    for (const actor of [id.actor, id.outsider]) await owner.query("INSERT INTO users(id,email_lookup_hash,email_ciphertext,password_hash,active) VALUES($1,$2,'synthetic-encrypted','synthetic-hash',true)", [actor, `tax-refresh-${actor}`]);
    await owner.query("INSERT INTO organization_memberships(id,organization_id,user_id,active) VALUES($1,$2,$3,true)", [id.member, id.org, id.actor]);
    await owner.query("INSERT INTO roles(id,organization_id,key,display_name,system_template) VALUES($1,$2,'TAX_REFRESH_TEST','Synthetic tax role',false)", [id.role, id.org]);
    await owner.query("INSERT INTO role_permissions(organization_id,role_id,permission_key) SELECT $1,$2,unnest($3::text[])", [id.org, id.role, ["mcp.ledger.read", "payables.read", "payables.manage", "payables.post", "payables.settle", "tax.determinations.override", "ledger.journal.draft", "ledger.journal.post"]]);
    await owner.query("INSERT INTO membership_roles(organization_id,membership_id,role_id,assigned_by) VALUES($1,$2,$3,$4)", [id.org, id.member, id.role, id.actor]);
    await owner.query("INSERT INTO legal_entities(id,organization_id,code,display_name,country_code,region_code) VALUES($1,$2,'TAX','Synthetic entity','CA','ON')", [id.entity, id.org]);
    await owner.query("INSERT INTO ledgers(id,organization_id,legal_entity_id,code,display_name,kind,accounting_profile,functional_currency) VALUES($1,$2,$3,'PRIMARY','Synthetic ledger','PRIMARY','CAN_ASPE','CAD')", [id.ledger, id.org, id.entity]);
    await owner.query("INSERT INTO fiscal_periods(id,organization_id,ledger_id,fiscal_year,period_number,label,starts_on,ends_on) VALUES($1,$2,$3,2025,12,'Synthetic annual period','2025-01-01','2025-12-31')", [id.period, id.org, id.ledger]);
    await owner.query(`INSERT INTO gl_accounts(id,organization_id,ledger_id,code,display_name,class,control_kind,postable,active,valid_from) VALUES
      ($1,$4,$5,'4100','Synthetic revenue','REVENUE','NONE',true,true,'2025-01-01'),
      ($2,$4,$5,'6200','New expense','EXPENSE','NONE',true,true,'2025-01-01'),
      ($3,$4,$5,'1000','Synthetic cash','ASSET','NONE',true,true,'2025-01-01')`, [id.revenue, id.expense, id.cash, id.org, id.ledger]);
    await owner.query("INSERT INTO account_combinations(id,organization_id,ledger_id,entity_id,account_id) VALUES($1,$3,$4,$5,$6),($2,$3,$4,$5,$7)", [id.expenseCombination, id.cashCombination, id.org, id.ledger, id.entity, id.expense, id.cash]);

 const root=loadOrganizationRootKek(),dek=randomBytes(32);try {const wrapped=new LocalRootKeyProvider(root).wrapOrganizationKey(id.org,1,dek);await owner.query("INSERT INTO organization_key_versions(organization_id,version,key_provider,wrapped_dek,active) VALUES($1,1,$2,$3,true)",[id.org,wrapped.provider,serializeWrappedKey(wrapped)]);
 const encrypted=serializeEncryptedField(encryptField("Synthetic supplier",dek,{organizationId:id.org,table:"parties",column:"display_name_ciphertext",recordId:id.party,keyVersion:1}));
 await owner.query("INSERT INTO parties(id,organization_id,party_number,display_name_ciphertext,display_name_key_version,search_token) VALUES($1,$2,'SUPPLIER',$3,1,'hmac-sha256-v1:'||repeat('a',64))",[id.party,id.org,encrypted]);
 const registration=serializeEncryptedField(encryptField("Synthetic GST reference",dek,{organizationId:id.org,table:"entity_tax_registrations",column:"registration_ciphertext",recordId:id.taxRegistration,keyVersion:1}));
 await owner.query("INSERT INTO entity_tax_registrations(id,organization_id,legal_entity_id,regime_key,destination_country,destination_region,registration_ciphertext,key_version,valid_from) VALUES($1,$2,$3,'ca.on.hst','CA','ON',$4,'1','2025-01-01')",[id.taxRegistration,id.org,id.entity,registration]);
 }finally{root.fill(0);dek.fill(0);}
 await owner.query("INSERT INTO gl_accounts(id,organization_id,ledger_id,code,display_name,class,control_kind,postable,active,valid_from) VALUES($1,$3,$4,'2100','Supplier payable','LIABILITY','AP',true,true,'2025-01-01'),($2,$3,$4,'2300','Shareholder or card liability','LIABILITY','NONE',true,true,'2025-01-01')",[id.payable,id.liability,id.org,id.ledger]);
 await owner.query("INSERT INTO account_combinations(id,organization_id,ledger_id,entity_id,account_id) VALUES($1,$3,$4,$5,$6),($2,$3,$4,$5,$7)",[id.payableCombination,id.liabilityCombination,id.org,id.ledger,id.entity,id.payable,id.liability]);
 await owner.query("INSERT INTO account_combinations(id,organization_id,ledger_id,entity_id,account_id) VALUES($1,$2,$3,$4,$5)",[id.gainCombination,id.org,id.ledger,id.entity,id.revenue]);
 await owner.query("INSERT INTO party_accounts(id,organization_id,legal_entity_id,ledger_id,party_id,role,account_number,control_account_id) VALUES($1,$2,$3,$4,$5,'SUPPLIER','SUPPLIER',$6)",[id.partyAccount,id.org,id.entity,id.ledger,id.party,id.payable]);
 },30000);
 afterAll(async()=>{await closeDatabasePool();await owner.end();vi.unstubAllEnvs();});
 it("captures an encrypted immutable draft and replays the same create without posting",async()=>{manual=await journalRecord();const args=batch([manual]);review=await createBookingBatch(context(),args);expect(review.status).toBe("DRAFT");expect(review.snapshot.entries[0].linesArePosted).toBe(false);expect((await createBookingBatch(context(),args)).reportId).toBe(review.reportId);await expect(createBookingBatch(context(),{...args,title:"Changed"})).rejects.toThrow(/Idempotency/);
 const raw=(await owner.query("SELECT snapshot_ciphertext FROM booking_batch_reports WHERE id=$1",[review.reportId])).rows[0];expect(raw.snapshot_ciphertext).not.toContain("Synthetic booked journal");expect((await owner.query("SELECT status FROM journal_entries WHERE id=$1",[manual.id])).rows[0].status).toBe("DRAFT");});
 it("posts through normal controls, saves actual lines and returns the same outcome on retry",async()=>{const args={batchId:review.batchId,reviewReportId:review.reportId,expectedReviewHash:review.hash,confirmed:true,reason:"Book reviewed synthetic journal",idempotencyKey:randomUUID()};await expect(postBookingBatch(context(),{...args,expectedReviewHash:"0".repeat(64)})).rejects.toThrow(/exact immutable/);
 const result=await postBookingBatch(context(),args);expect(result).not.toHaveProperty("reportGenerationRequired");posted=result as BookingReport;expect(posted.status).toBe("POSTED");expect(posted.snapshot.entries[0]).toMatchObject({status:"POSTED",linesArePosted:true});expect(posted.snapshot.entries[0].journalNumber).toBeTypeOf("number");expect((await postBookingBatch(context(),args) as BookingReport).reportId).toBe(posted.reportId);
 expect((await readBookingReport(context(),{batchId:review.batchId,reportId:review.reportId})).status).toBe("DRAFT");expect((await owner.query("SELECT count(*)::int AS n FROM journal_entries WHERE id=$1",[manual.id])).rows[0].n).toBe(1);});
 it("enforces tenant, company, active role and append-only permissions",async()=>{await expect(readBookingReport({...context(),organizationId:randomUUID()},{batchId:review.batchId})).rejects.toThrow();await expect(readBookingReport({...context(),actorId:id.outsider},{batchId:review.batchId})).rejects.toThrow();await expect(createBookingBatch(context(),{...batch([manual]),legalEntityId:randomUUID()})).rejects.toThrow();
 await expect(withTenantTransaction(context(),client=>client.query("UPDATE booking_batch_reports SET status='DRAFT' WHERE id=$1",[posted.reportId]))).rejects.toThrow();await expect(withTenantTransaction(context(),client=>client.query("DELETE FROM booking_batches WHERE id=$1",[review.batchId]))).rejects.toThrow();
 expect((await withTenantTransaction({...context(),organizationId:randomUUID()},client=>client.query("SELECT id FROM booking_batches WHERE id=$1",[review.batchId]))).rows).toHaveLength(0);
 expect(await listBookingReports(context(),{journalId:manual.id})).toEqual([expect.objectContaining({batchId:review.batchId})]);});
 it("detects intervening edits, holds changed entries and records partial completion",async()=>{const good=await journalRecord(),changed=await journalRecord("Change after review");const initial=await createBookingBatch(context(),batch([good,changed]));
 await withTenantTransaction(context(),client=>client.query("UPDATE journal_entries SET description='Changed after immutable review' WHERE organization_id=$1 AND id=$2",[id.org,changed.id]));
 const result=await postBookingBatch(context(),{batchId:initial.batchId,reviewReportId:initial.reportId,expectedReviewHash:initial.hash,confirmed:true,reason:"Only unchanged entry may book",idempotencyKey:randomUUID()}) as BookingReport;
 expect(result.status).toBe("PARTIALLY_POSTED");expect(result.completeness).toBe("STALE");expect(result.snapshot.entries.find(entry=>entry.id===changed.id)?.differences.length).toBeGreaterThan(0);expect((await owner.query("SELECT status FROM journal_entries WHERE id=$1",[changed.id])).rows[0].status).toBe("DRAFT");
 const refreshed=await refreshBookingReport(context(),{batchId:initial.batchId,reason:"Recover outcome without booking",idempotencyKey:randomUUID()});expect(refreshed.status).toBe("PARTIALLY_POSTED");expect(refreshed.version).toBe(3);});
 it("recovers a report after accounting committed without repeating journal posting",async()=>{const record=await journalRecord(),initial=await createBookingBatch(context(),batch([record]));await postJournal({context:context(),journalId:record.id,expectedContentHash:record.expectedContentHash});const before=(await owner.query("SELECT count(*)::int AS n FROM journal_entries WHERE organization_id=$1",[id.org])).rows[0].n;
 const args={batchId:initial.batchId,reason:"Capture previously committed outcome",idempotencyKey:randomUUID()};const result=await refreshBookingReport(context(),args);expect(result.status).toBe("POSTED");expect((await refreshBookingReport(context(),args)).reportId).toBe(result.reportId);expect((await owner.query("SELECT count(*)::int AS n FROM journal_entries WHERE organization_id=$1",[id.org])).rows[0].n).toBe(before);});
 it("returns a recoverable result when report generation fails after posting",async()=>{const record=await journalRecord(),initial=await createBookingBatch(context(),batch([record]));const unavailable=vi.spyOn(capture,"captureBookingSnapshot").mockRejectedValueOnce(new Error("Synthetic reporting outage"));
 const args={batchId:initial.batchId,reviewReportId:initial.reportId,expectedReviewHash:initial.hash,confirmed:true,reason:"Book despite later report outage",idempotencyKey:randomUUID()};
 try {expect(await postBookingBatch(context(),args)).toMatchObject({batchId:initial.batchId,reportGenerationRequired:true});}finally{unavailable.mockRestore();}
 const before=(await owner.query("SELECT journal_number FROM journal_entries WHERE id=$1",[record.id])).rows[0].journal_number;expect(before).toBeTypeOf("number");
 const recovered=await postBookingBatch(context(),args) as BookingReport;expect(recovered.status).toBe("POSTED");expect(recovered.snapshot.entries[0].journalNumber).toBe(before);
 });
 it("reports signed multicurrency source lines and original source versions",async()=>{const snap=buildBusinessDocumentSnapshot({kind:"SUPPLIER_BILL",sourceNumber:"SYNTHETIC-USD",ledgerId:id.ledger,legalEntityId:id.entity,partyAccountId:id.partyAccount,controlAccountCombinationId:id.payableCombination,documentDate:"2025-12-15",accountingDate:"2025-12-15",periodId:id.period,dueOn:"2025-12-31",currency:"USD",fx:{rate:"1.37",source:"MANUAL",effectiveAt:"2025-12-15T00:00:00Z",quoteConvention:"FUNCTIONAL_UNITS_PER_TRANSACTION_UNIT"},description:"Synthetic subscription net of credit",lines:[{description:"Charge",accountCombinationId:id.expenseCombination,netAmount:"100",tax:{packKey:"ca.on.hst",category:"OUT_OF_SCOPE",destinationCountry:"CA",destinationRegion:"ON",registrationId:id.taxRegistration}},{description:"Credit",lineType:"ADJUSTMENT",accountCombinationId:id.expenseCombination,netAmount:"-20",tax:{packKey:"ca.on.hst",category:"OUT_OF_SCOPE",destinationCountry:"CA",destinationRegion:"ON",registrationId:id.taxRegistration}}]},"CAD");
 const row=await withTenantTransaction(context(),client=>appendSourceDocument(client,{context:context(),ownerModule:"payables",sourceType:"payables.supplier-bill",sourceNumber:snap.sourceNumber,legalEntityId:id.entity,version:1,status:"DRAFT",snapshot:snap,idempotencyKey:randomUUID(),commandHash:"a".repeat(64)}));
 const selected={type:"SOURCE_DOCUMENT" as const,id:row.id,expectedVersion:row.version,expectedContentHash:row.content_hash};const result=await createBookingBatch(context(),batch([selected]));expect(result.snapshot.entries[0]).toMatchObject({currency:"USD",gross:"80.00",grossFunctional:"109.60",party:"Synthetic supplier",linesArePosted:false});expect(result.snapshot.entries[0].lines.some(line=>line.credit==="20.00")).toBe(true);
 const issued=await issueBusinessDocument({context:context(),kind:"SUPPLIER_BILL",sourceNumber:snap.sourceNumber,expectedVersion:1,idempotencyKey:randomUUID()});
 for(const method of ["SHAREHOLDER_ADVANCE","CORPORATE_CARD"] as const){const settlement=await recordCustomerReceiptOrSupplierPayment({context:context(),kind:"SUPPLIER_PAYMENT",sourceNumber:`SYNTHETIC-${method}`,ledgerId:id.ledger,legalEntityId:id.entity,partyAccountId:id.partyAccount,controlAccountCombinationId:id.payableCombination,periodId:id.period,accountingDate:"2025-12-15",settlementDate:"2025-12-15",currency:"USD",amount:"20",fx:{rate:"1.37",source:"MANUAL",effectiveAt:"2025-12-15T00:00:00Z",quoteConvention:"FUNCTIONAL_UNITS_PER_TRANSACTION_UNIT"},settlementAccountCombinationId:id.liabilityCombination,settlementMethod:method,realizedFxGainAccountCombinationId:id.gainCombination,realizedFxLossAccountCombinationId:id.expenseCombination,description:"Synthetic non-cash settlement",allocations:[{openItemId:issued.openItemId,transactionAmount:"20"}],idempotencyKey:randomUUID()});
 const report=await createBookingBatch(context(),batch([{type:"SOURCE_DOCUMENT",id:settlement.document.id,expectedVersion:settlement.document.version,expectedContentHash:settlement.document.contentHash}]));expect(report.snapshot.entries[0].treatments.join(" ")).toContain(method==="CORPORATE_CARD"?"card provider":"shareholder");expect(report.snapshot.entries[0].linesArePosted).toBe(true);}
 const outcome=await refreshBookingReport(context(),{batchId:result.batchId,reason:"Read actual settled supplier bill",idempotencyKey:randomUUID()});expect(outcome.status).toBe("POSTED");expect(outcome.snapshot.entries[0].outstanding).toMatch(/^40(?:\.0+)?$/);expect(outcome.snapshot.summary.recognizedFunctional).toBe("109.6");expect(outcome.snapshot.entries[0].journalId).toBe(issued.journalId);
 const rounded=buildBusinessDocumentSnapshot({kind:"SUPPLIER_BILL",sourceNumber:"SYNTHETIC-ROUNDING",ledgerId:id.ledger,legalEntityId:id.entity,partyAccountId:id.partyAccount,controlAccountCombinationId:id.payableCombination,taxAccountCombinationId:id.cashCombination,documentDate:"2025-12-15",accountingDate:"2025-12-15",periodId:id.period,dueOn:"2025-12-31",currency:"CAD",fx:{rate:"1",source:"FUNCTIONAL",effectiveAt:"2025-12-15T00:00:00Z",quoteConvention:"FUNCTIONAL_UNITS_PER_TRANSACTION_UNIT"},description:"Synthetic reviewed supplier rounding",lines:[
 {description:"Charge",accountCombinationId:id.expenseCombination,netAmount:"85",tax:{packKey:"ca.on.hst",category:"STANDARD",destinationCountry:"CA",destinationRegion:"ON",registrationId:id.taxRegistration,recoverablePercent:"50"}},
 {description:"Credit",lineType:"ADJUSTMENT",accountCombinationId:id.expenseCombination,netAmount:"-33.87",tax:{packKey:"ca.on.hst",category:"STANDARD",destinationCountry:"CA",destinationRegion:"ON",registrationId:id.taxRegistration,recoverablePercent:"50",sourceTaxRounding:{amount:"-4.41",reason:"Printed source rounding verified",evidenceReference:"synthetic-invoice.pdf",reviewed:true}}}]},"CAD");
 const roundedSource=await withTenantTransaction(context(),client=>appendSourceDocument(client,{context:context(),ownerModule:"payables",sourceType:"payables.supplier-bill",sourceNumber:rounded.sourceNumber,legalEntityId:id.entity,version:1,status:"DRAFT",snapshot:rounded,idempotencyKey:randomUUID(),commandHash:"b".repeat(64)}));
 const roundedReview=await createBookingBatch(context(),batch([{type:"SOURCE_DOCUMENT",id:roundedSource.id,expectedVersion:1,expectedContentHash:roundedSource.content_hash}]));
 expect(roundedReview.snapshot.entries[0].taxDetails[1]).toMatchObject({tax:"-4.41",rounding:"-0.01",evidence:"synthetic-invoice.pdf"});expect(roundedReview.snapshot.entries[0].taxDetails[0].treatment).toContain("NONRECOVERABLE");
 const roundedOutcome=await postBookingBatch(context(),{batchId:roundedReview.batchId,reviewReportId:roundedReview.reportId,expectedReviewHash:roundedReview.hash,confirmed:true,reason:"Book reviewed rounded invoice",idempotencyKey:randomUUID()}) as BookingReport;
 expect(roundedOutcome.status).toBe("POSTED");expect(roundedOutcome.snapshot.entries[0]).toMatchObject({gross:"57.77",tax:"6.64",net:"51.13",linesArePosted:true});
 await owner.query("DELETE FROM role_permissions WHERE organization_id=$1 AND role_id=$2 AND permission_key='payables.read'",[id.org,id.role]);await expect(readBookingReport(context(),{batchId:result.batchId})).rejects.toThrow();
 },30000);
});
