import { renderAccountKey } from "@/modules/ledger/account-segments";
import { decideTax } from "@/modules/tax/engine";

const ontarioTax = decideTax("ca.on.hst", {
  direction: "SALE",
  taxPointDate: "2026-08-26",
  currency: "CAD",
  taxableBasis: "100",
  destinationCountry: "CA",
  destinationRegion: "ON",
  category: "STANDARD",
  registrationId: "demo-ca-registration",
});

const seattleTax = decideTax("us.wa.sales-use", {
  direction: "SALE",
  taxPointDate: "2026-08-26",
  currency: "USD",
  taxableBasis: "100",
  destinationCountry: "US",
  destinationRegion: "WA",
  destinationCity: "Seattle",
  locationCode: "1726",
  category: "STANDARD",
});

export const demoDashboard = {
  organization: {
    name: "Northstar Demo Group",
    environment: "Demo business",
    currentDate: "August 26, 2026",
  },
  entities: [
    {
      code: "CA01",
      name: "Northstar Services Canada Inc.",
      location: "Ontario, Canada",
      profile: "Canadian ASPE",
      currency: "CAD",
      period: "Aug 2026",
      periodState: "OPEN",
      periodTone: "open",
      trialBalance: "$428,640.00",
      openReceivables: "$84,210.35",
      openPayables: "$41,870.12",
      closeProgress: 68,
    },
    {
      code: "US01",
      name: "Northstar Services USA LLC",
      location: "Washington, United States",
      profile: "U.S. GAAP · non-public",
      currency: "USD",
      period: "Aug 2026",
      periodState: "ADJUSTMENT ONLY",
      periodTone: "adjustment",
      trialBalance: "$312,980.00",
      openReceivables: "$65,590.20",
      openPayables: "$37,430.48",
      closeProgress: 92,
    },
  ],
  metrics: [
    {
      label: "Receivables",
      values: ["CAD 84,210", "USD 65,590"],
      note: "23 open items · 4 overdue",
      tone: "blue",
    },
    {
      label: "Payables",
      values: ["CAD 41,870", "USD 37,430"],
      note: "16 open items · 3 due this week",
      tone: "amber",
    },
    {
      label: "Drafts to review",
      values: ["8 documents"],
      note: "5 user · 2 import · 1 MCP",
      tone: "purple",
    },
    {
      label: "Control status",
      values: ["All balanced"],
      note: "Last validation 2 minutes ago",
      tone: "green",
    },
  ],
  journals: [
    {
      number: "CA-000291",
      date: "Aug 26",
      entity: "CA01",
      type: "Sales invoice",
      typeKey: "receivables.sales-invoice",
      source: "INV-1048",
      amount: "CAD 11,300.00",
      status: "POSTED",
      owner: "Receivables",
    },
    {
      number: "US-000188",
      date: "Aug 26",
      entity: "US01",
      type: "Supplier bill",
      typeKey: "payables.supplier-bill",
      source: "BILL-0882",
      amount: "USD 4,850.00",
      status: "POSTED",
      owner: "Payables",
    },
    {
      number: "Draft",
      date: "Aug 26",
      entity: "CA01",
      type: "Manual journal",
      typeKey: "ledger.manual",
      source: "MCP-DRAFT-17",
      amount: "CAD 1,250.00",
      status: "REVIEW",
      owner: "General ledger",
    },
    {
      number: "CA-000290",
      date: "Aug 25",
      entity: "CA01",
      type: "Full reversal",
      typeKey: "ledger.full-reversal",
      source: "Reverses CA-000284",
      amount: "CAD 730.25",
      status: "POSTED",
      owner: "Ledger kernel",
    },
  ],
  accountExample: {
    canonicalKey: renderAccountKey({
      entity: "CA01",
      account: "6100",
      subaccount: "SERV",
      department: "OPS",
      intercompany: null,
      custom1: "CONS",
      custom2: "DIRECT",
      custom3: null,
      custom4: null,
      custom5: null,
      custom6: null,
      custom7: null,
      custom8: null,
    }),
    segments: [
      ["Entity", "CA01"],
      ["Account", "6100"],
      ["Subaccount", "SERV"],
      ["Department", "OPS"],
      ["Intercompany", "0000"],
      ["Service line", "CONS"],
      ["Channel", "DIRECT"],
      ["Custom 3–8", "Hidden · 0000"],
    ],
  },
  parties: [
    {
      party: "P:000184",
      name: "Harbour Dental Group",
      roles: ["C:CA-0021"],
      entity: "CA01",
      balance: "CAD 18,420.00 AR",
    },
    {
      party: "P:000203",
      name: "Cascade Office Supply",
      roles: ["C:US-0018", "S:US-0044"],
      entity: "US01",
      balance: "USD 6,180 AR · 2,410 AP",
    },
    {
      party: "P:000219",
      name: "Northstar Services USA LLC",
      roles: ["S:CA-0072", "IC:US01"],
      entity: "CA01 ↔ US01",
      balance: "CAD 9,240 intercompany",
    },
  ],
  taxDecisions: [
    {
      jurisdiction: "Ontario HST",
      pack: `${ontarioTax.packKey} · ${ontarioTax.packVersion}`,
      rate: "13.00%",
      result: `CAD ${ontarioTax.totalTax}`,
      status: ontarioTax.status,
      note: "One legal HST component · CRA place of supply",
    },
    {
      jurisdiction: "Seattle sales tax",
      pack: `${seattleTax.packKey} · ${seattleTax.packVersion}`,
      rate: "10.55%",
      result: `USD ${seattleTax.totalTax}`,
      status: seattleTax.status,
      note: "6.50 state + 4.05 local · DOR location 1726",
    },
  ],
  closeChecklist: [
    { label: "All journals balanced", done: true, detail: "479 posted entries" },
    { label: "AR/AP controls reconciled", done: true, detail: "No variance" },
    { label: "Tax exceptions cleared", done: false, detail: "2 require review" },
    { label: "Bank reconciliation", done: false, detail: "Module deferred" },
  ],
} as const;
