import type { QueryResult } from "pg";
import { journalTypeRegistry } from "@/modules/registry";

export type JournalTypeDatabaseDefinition = Readonly<{
  id: string;
  key: string;
  version: number;
  ownerModule: string;
  displayName: string;
  correctionRoute: string;
}>;

type JournalTypeQuery = (
  text: string,
) => Promise<Pick<QueryResult<JournalTypeDatabaseDefinition>, "rows">>;

export const JOURNAL_TYPE_REGISTRY_SELECT = `
  SELECT id::text AS id, key, version,
    owner_module AS "ownerModule",
    display_name AS "displayName",
    correction_route AS "correctionRoute"
  FROM journal_type_definitions
  ORDER BY key, version`;

export const journalTypeSeedDefinitions: readonly JournalTypeDatabaseDefinition[] =
  journalTypeRegistry.list().map((definition) => ({
    id: definition.id,
    key: definition.key,
    version: definition.version,
    ownerModule: definition.ownerModule,
    displayName: definition.label,
    correctionRoute: definition.correctionRoute,
  }));

function identity(definition: Pick<JournalTypeDatabaseDefinition, "key" | "version">): string {
  return `${definition.key}@${definition.version}`;
}

function sorted(
  definitions: readonly JournalTypeDatabaseDefinition[],
): readonly JournalTypeDatabaseDefinition[] {
  return [...definitions].sort((left, right) => {
    const keyOrder = left.key < right.key ? -1 : left.key > right.key ? 1 : 0;
    return keyOrder || left.version - right.version;
  });
}

export function findJournalTypeRegistryDrift(
  databaseDefinitions: readonly JournalTypeDatabaseDefinition[],
  expectedDefinitions: readonly JournalTypeDatabaseDefinition[] = journalTypeSeedDefinitions,
): readonly string[] {
  const expectedByIdentity = new Map(
    sorted(expectedDefinitions).map((definition) => [identity(definition), definition]),
  );
  const databaseByIdentity = new Map(
    sorted(databaseDefinitions).map((definition) => [identity(definition), definition]),
  );
  const diagnostics: string[] = [];

  for (const [definitionIdentity, expected] of expectedByIdentity) {
    const actual = databaseByIdentity.get(definitionIdentity);
    if (!actual) {
      diagnostics.push(`database is missing manifest journal type ${definitionIdentity}`);
      continue;
    }

    for (const field of ["id", "ownerModule", "displayName", "correctionRoute"] as const) {
      if (actual[field] !== expected[field]) {
        diagnostics.push(
          `${definitionIdentity} ${field} is ${JSON.stringify(actual[field])}; manifest requires ${JSON.stringify(expected[field])}`,
        );
      }
    }
  }

  for (const definitionIdentity of databaseByIdentity.keys()) {
    if (!expectedByIdentity.has(definitionIdentity)) {
      diagnostics.push(`database has unregistered journal type ${definitionIdentity}`);
    }
  }

  return diagnostics.sort();
}

export function assertJournalTypeRegistryRows(
  databaseDefinitions: readonly JournalTypeDatabaseDefinition[],
  expectedDefinitions: readonly JournalTypeDatabaseDefinition[] = journalTypeSeedDefinitions,
): void {
  const diagnostics = findJournalTypeRegistryDrift(databaseDefinitions, expectedDefinitions);
  if (diagnostics.length > 0) {
    throw new Error(
      `Journal type registry drift (${diagnostics.length} mismatch(es)):\n${diagnostics.map((item) => `- ${item}`).join("\n")}`,
    );
  }
}

export async function assertJournalTypeRegistryDatabase(query: JournalTypeQuery): Promise<void> {
  const result = await query(JOURNAL_TYPE_REGISTRY_SELECT);
  assertJournalTypeRegistryRows(result.rows);
}

function sqlLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function renderJournalTypeSeedSql(
  definitions: readonly JournalTypeDatabaseDefinition[] = journalTypeSeedDefinitions,
): string {
  const values = sorted(definitions).map((definition) =>
    `  (${sqlLiteral(definition.id)}, ${sqlLiteral(definition.key)}, ${definition.version}, ${sqlLiteral(definition.ownerModule)}, ${sqlLiteral(definition.displayName)}, ${sqlLiteral(definition.correctionRoute)})`,
  );
  if (values.length === 0) throw new Error("The journal type seed contract cannot be empty");

  return [
    "-- GENERATED by `npm run journal-types:generate-seed` from the enabled module manifests.",
    "-- Copy the reviewed statement into a forward migration when adding a journal type.",
    "-- Do not edit this artifact by hand.",
    "INSERT INTO journal_type_definitions (id, key, version, owner_module, display_name, correction_route)",
    "VALUES",
    `${values.join(",\n")}`,
    "ON CONFLICT (key, version) DO UPDATE SET",
    "  owner_module = EXCLUDED.owner_module,",
    "  display_name = EXCLUDED.display_name,",
    "  correction_route = EXCLUDED.correction_route;",
    "",
  ].join("\n");
}
