Foreground yes
LocalSocket /tmp/clamd.sock
TCPSocket 3310
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LogTime yes
StreamMaxLength 2M
MaxFileSize 16M
MaxScanSize 32M
MaxRecursion 10
MaxFiles 1000
MaxScanTime 10000
MaxThreads 2
MaxQueue 4
ReadTimeout 15
CommandReadTimeout 5
ConcurrentDatabaseReload no
SelfCheck 600
ScanPDF yes
AlertEncrypted yes
AlertExceedsMax yes
EnableShutdownCommand no
FailIfCvdOlderThan 7
